// 
// <auto-generated>
//     This code was generated by a tool.
//     Do not modify this file directly.
// </auto-generated>
// 
// $FILENAME
// 
//   Generated: $TIMESTAMP
// 
//   $AUTHORS
//      $AUTHOR_URL
//
//   Copyright © $YEAR $COPYRIGHT_OWNER, All Rights Reserved
//      License: $LICENSE (https://opensource.org/licenses/$LICENSE)
// 
